name: Sync Upstream and Trigger Release

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码并配置稀疏检出
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !.github/workflows/
          sparse-checkout-cone-mode: false

      - name: 配置上游仓库并同步更改
        run: |
          git remote add upstream https://github.com/Ziayongyao/Sesame-TK.git || true
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch upstream
          git pull --rebase upstream main -X theirs
          git push origin HEAD:main --force-with-lease

      - name: 触发发布工作流
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Release_APKs.yml',
              ref: 'main'
            })